export type CompanySeed = {
  symbol: string;
  name: string;
  sector: string;
  description: string;
  owner_name: string;
  employee_count: number;
  founded_year: number;
  government_support_type: string;
  government_support_amount: number;
  tax_benefit_percent: number;
  state_loan_rate_percent: number;
  support_expires_year: number;
  support_risk_level: string;
  price: number;
  previous_price: number;
  market_cap: number;
  volatility: number;
  event_sensitivity: number;
};

export type BotTraderSeed = {
  name: string;
  cash_balance: number;
  style:
    | 'scalper'
    | 'investor'
    | 'panic'
    | 'aggressive'
    | 'market_maker'
    | 'random'
    | 'momentum'
    | 'value'
    | 'support'
    | 'contrarian'
    | 'balanced';
};

export type EventTemplateSeed = {
  title: string;
  description: string;
  category: string;
  scope: 'global' | 'sector' | 'company';
  target_sector?: string;
  target_symbol?: string;
  price_impact_percent: number;
  sector_impacts?: Record<string, number>;
};

export const SECTOR_CONFIG = {
  AI: { rateSensitivity: -1.1, warSensitivity: 0.2, techSensitivity: 1.2 },
  Robotics: {
    rateSensitivity: -0.8,
    warSensitivity: 0.5,
    techSensitivity: 1.1,
  },
  Banking: {
    rateSensitivity: 1.2,
    warSensitivity: -0.4,
    techSensitivity: -0.1,
  },
  Logistics: {
    rateSensitivity: -0.2,
    warSensitivity: -1.1,
    techSensitivity: 0.2,
  },
  Space: { rateSensitivity: -1.0, warSensitivity: 0.7, techSensitivity: 1.0 },
  Gaming: { rateSensitivity: -0.6, warSensitivity: -0.3, techSensitivity: 0.6 },
  Energy: { rateSensitivity: 0.1, warSensitivity: 0.9, techSensitivity: 0.2 },
  Biotech: {
    rateSensitivity: -0.9,
    warSensitivity: -0.2,
    techSensitivity: 1.0,
  },
  Semiconductor: {
    rateSensitivity: -0.8,
    warSensitivity: -0.5,
    techSensitivity: 1.3,
  },
  Automotive: {
    rateSensitivity: -0.7,
    warSensitivity: -0.5,
    techSensitivity: 0.5,
  },
  Telecom: { rateSensitivity: -0.2, warSensitivity: 0.1, techSensitivity: 0.4 },
  Retail: { rateSensitivity: -0.6, warSensitivity: -0.4, techSensitivity: 0.1 },
  Agriculture: {
    rateSensitivity: -0.1,
    warSensitivity: 0.0,
    techSensitivity: 0.3,
  },
  Mining: { rateSensitivity: 0.2, warSensitivity: 0.7, techSensitivity: -0.1 },
  Cloud: { rateSensitivity: -1.0, warSensitivity: -0.1, techSensitivity: 1.1 },
  Cybersecurity: {
    rateSensitivity: -0.4,
    warSensitivity: 0.8,
    techSensitivity: 1.0,
  },
  Education: {
    rateSensitivity: -0.4,
    warSensitivity: -0.1,
    techSensitivity: 0.5,
  },
  Manufacturing: {
    rateSensitivity: -0.5,
    warSensitivity: -0.5,
    techSensitivity: 0.2,
  },
  Fintech: {
    rateSensitivity: -0.8,
    warSensitivity: -0.2,
    techSensitivity: 0.8,
  },
  Consumer: {
    rateSensitivity: -0.5,
    warSensitivity: -0.3,
    techSensitivity: 0.1,
  },
} as const;

export const MARKET_COMPANIES: CompanySeed[] = [
  {
    symbol: 'NOVA',
    name: 'Nova Robotics',
    sector: 'AI',
    description:
      'Builds autonomous warehouse robots and machine-vision systems for logistics companies.',
    owner_name: 'Maya Levin',
    employee_count: 1240,
    founded_year: 2017,
    government_support_type: 'R&D grant',
    government_support_amount: 18000000,
    tax_benefit_percent: 8,
    state_loan_rate_percent: 0,
    support_expires_year: 2029,
    support_risk_level: 'medium',
    price: 42,
    previous_price: 42,
    market_cap: 420000000,
    volatility: 4.5,
    event_sensitivity: 1.15,
  },
  {
    symbol: 'SOLR',
    name: 'Solara Grid',
    sector: 'Energy',
    description:
      'Operates smart solar microgrids and battery balancing software for midsize cities.',
    owner_name: 'Daniel Cross',
    employee_count: 860,
    founded_year: 2014,
    government_support_type: 'Green energy tax credit',
    government_support_amount: 24000000,
    tax_benefit_percent: 14,
    state_loan_rate_percent: 2.1,
    support_expires_year: 2031,
    support_risk_level: 'low',
    price: 26,
    previous_price: 26,
    market_cap: 260000000,
    volatility: 3.25,
    event_sensitivity: 0.85,
  },
  {
    symbol: 'MEDX',
    name: 'Medix Labs',
    sector: 'Healthcare',
    description:
      'Develops diagnostic lab tools and AI-assisted screening kits for clinics.',
    owner_name: 'Dr. Elena Mor',
    employee_count: 530,
    founded_year: 2019,
    government_support_type: 'Health innovation grant',
    government_support_amount: 9000000,
    tax_benefit_percent: 5,
    state_loan_rate_percent: 0,
    support_expires_year: 2028,
    support_risk_level: 'medium',
    price: 18,
    previous_price: 18,
    market_cap: 180000000,
    volatility: 5.1,
    event_sensitivity: 1.05,
  },
  {
    symbol: 'BYTE',
    name: 'ByteForge Games',
    sector: 'Gaming',
    description:
      'Publishes competitive mobile games and live-service economies for esports fans.',
    owner_name: 'Noam Adler',
    employee_count: 410,
    founded_year: 2021,
    government_support_type: 'none',
    government_support_amount: 0,
    tax_benefit_percent: 0,
    state_loan_rate_percent: 0,
    support_expires_year: 0,
    support_risk_level: 'none',
    price: 12,
    previous_price: 12,
    market_cap: 120000000,
    volatility: 6,
    event_sensitivity: 1.25,
  },
  {
    symbol: 'AERO',
    name: 'AeroVista Drones',
    sector: 'Space',
    description:
      'Makes inspection drones for ports, farms, and construction sites with long-range sensors.',
    owner_name: 'Sofia Grant',
    employee_count: 720,
    founded_year: 2016,
    government_support_type: 'Defense supplier credit line',
    government_support_amount: 32000000,
    tax_benefit_percent: 6,
    state_loan_rate_percent: 1.8,
    support_expires_year: 2030,
    support_risk_level: 'medium',
    price: 31,
    previous_price: 31,
    market_cap: 310000000,
    volatility: 4.8,
    event_sensitivity: 1.05,
  },
  {
    symbol: 'FARM',
    name: 'FarmPulse Foods',
    sector: 'Agriculture',
    description:
      'Runs vertical farms and crop analytics for supermarkets seeking local produce supply.',
    owner_name: 'Ilan Becker',
    employee_count: 640,
    founded_year: 2015,
    government_support_type: 'Food security subsidy',
    government_support_amount: 14000000,
    tax_benefit_percent: 10,
    state_loan_rate_percent: 2.4,
    support_expires_year: 2027,
    support_risk_level: 'high',
    price: 15,
    previous_price: 15,
    market_cap: 150000000,
    volatility: 3.9,
    event_sensitivity: 0.95,
  },
  {
    symbol: 'FINX',
    name: 'FinAxis Pay',
    sector: 'Fintech',
    description:
      'Provides simulated payment rails, fraud scoring, and merchant settlement tools.',
    owner_name: 'Ari Stone',
    employee_count: 1180,
    founded_year: 2013,
    government_support_type: 'none',
    government_support_amount: 0,
    tax_benefit_percent: 0,
    state_loan_rate_percent: 0,
    support_expires_year: 0,
    support_risk_level: 'none',
    price: 38,
    previous_price: 38,
    market_cap: 380000000,
    volatility: 5.4,
    event_sensitivity: 1.15,
  },
  {
    symbol: 'EDU',
    name: 'EduCore Cloud',
    sector: 'Education',
    description:
      'Sells learning platforms, exams, and analytics dashboards to schools and bootcamps.',
    owner_name: 'Rachel Kim',
    employee_count: 350,
    founded_year: 2018,
    government_support_type: 'Education modernization tender',
    government_support_amount: 7000000,
    tax_benefit_percent: 4,
    state_loan_rate_percent: 0,
    support_expires_year: 2028,
    support_risk_level: 'low',
    price: 11,
    previous_price: 11,
    market_cap: 110000000,
    volatility: 4.1,
    event_sensitivity: 0.9,
  },
  {
    symbol: 'CYBR',
    name: 'CipherWall Security',
    sector: 'Cybersecurity',
    description:
      'Protects small businesses with endpoint defense, password audits, and incident response.',
    owner_name: 'Victor Hale',
    employee_count: 970,
    founded_year: 2012,
    government_support_type: 'Critical infrastructure contract',
    government_support_amount: 21000000,
    tax_benefit_percent: 3,
    state_loan_rate_percent: 1.5,
    support_expires_year: 2029,
    support_risk_level: 'medium',
    price: 47,
    previous_price: 47,
    market_cap: 470000000,
    volatility: 5.7,
    event_sensitivity: 1.1,
  },
  {
    symbol: 'OCEA',
    name: 'OceanArc Shipping',
    sector: 'Logistics',
    description:
      'Coordinates container routes, port scheduling, and fuel optimization for regional fleets.',
    owner_name: 'Lina Torres',
    employee_count: 1540,
    founded_year: 2009,
    government_support_type: 'Port logistics loan',
    government_support_amount: 26000000,
    tax_benefit_percent: 2,
    state_loan_rate_percent: 2.8,
    support_expires_year: 2032,
    support_risk_level: 'low',
    price: 21,
    previous_price: 21,
    market_cap: 210000000,
    volatility: 3.6,
    event_sensitivity: 1,
  },
  {
    symbol: 'FOAM',
    name: 'FoamLite Materials',
    sector: 'Manufacturing',
    description:
      'Produces lightweight insulation panels and recyclable packaging materials.',
    owner_name: 'Peter Novak',
    employee_count: 780,
    founded_year: 2011,
    government_support_type: 'Manufacturing tax relief',
    government_support_amount: 11000000,
    tax_benefit_percent: 9,
    state_loan_rate_percent: 0,
    support_expires_year: 2026,
    support_risk_level: 'high',
    price: 17,
    previous_price: 17,
    market_cap: 170000000,
    volatility: 4.4,
    event_sensitivity: 1,
  },
  {
    symbol: 'LUX',
    name: 'Luxora Retail',
    sector: 'Retail',
    description:
      'Runs premium lifestyle stores and a direct-to-consumer brand marketplace.',
    owner_name: 'Nadia Wells',
    employee_count: 1320,
    founded_year: 2010,
    government_support_type: 'none',
    government_support_amount: 0,
    tax_benefit_percent: 0,
    state_loan_rate_percent: 0,
    support_expires_year: 0,
    support_risk_level: 'none',
    price: 24,
    previous_price: 24,
    market_cap: 240000000,
    volatility: 4.9,
    event_sensitivity: 1,
  },
  {
    symbol: 'QUAN',
    name: 'Quantica AI',
    sector: 'AI',
    description:
      'Builds market simulation engines and enterprise forecasting tools.',
    owner_name: 'Leah Stern',
    employee_count: 680,
    founded_year: 2020,
    government_support_type: 'AI safety grant',
    government_support_amount: 12000000,
    tax_benefit_percent: 6,
    state_loan_rate_percent: 0,
    support_expires_year: 2029,
    support_risk_level: 'medium',
    price: 34,
    previous_price: 34,
    market_cap: 340000000,
    volatility: 5.4,
    event_sensitivity: 1.2,
  },
  {
    symbol: 'MECH',
    name: 'MechaLine Systems',
    sector: 'Robotics',
    description:
      'Manufactures industrial robot arms for factories and warehouses.',
    owner_name: 'Jonas Meier',
    employee_count: 2100,
    founded_year: 2008,
    government_support_type: 'Automation loan',
    government_support_amount: 16000000,
    tax_benefit_percent: 5,
    state_loan_rate_percent: 2.2,
    support_expires_year: 2030,
    support_risk_level: 'low',
    price: 29,
    previous_price: 29,
    market_cap: 430000000,
    volatility: 4.6,
    event_sensitivity: 1.05,
  },
  {
    symbol: 'BRIX',
    name: 'Brixon Bank',
    sector: 'Banking',
    description:
      'Operates a digital-first commercial bank for small companies.',
    owner_name: 'Marcus Hale',
    employee_count: 3900,
    founded_year: 1998,
    government_support_type: 'none',
    government_support_amount: 0,
    tax_benefit_percent: 0,
    state_loan_rate_percent: 0,
    support_expires_year: 0,
    support_risk_level: 'none',
    price: 51,
    previous_price: 51,
    market_cap: 980000000,
    volatility: 3.2,
    event_sensitivity: 0.85,
  },
  {
    symbol: 'ORBT',
    name: 'OrbitalBridge',
    sector: 'Space',
    description:
      'Launches small satellites and leases orbital communication capacity.',
    owner_name: 'Amara Cole',
    employee_count: 1120,
    founded_year: 2016,
    government_support_type: 'Satellite security contract',
    government_support_amount: 28000000,
    tax_benefit_percent: 4,
    state_loan_rate_percent: 1.9,
    support_expires_year: 2032,
    support_risk_level: 'medium',
    price: 63,
    previous_price: 63,
    market_cap: 720000000,
    volatility: 5.8,
    event_sensitivity: 1.25,
  },
  {
    symbol: 'GENE',
    name: 'GenePeak Bio',
    sector: 'Biotech',
    description:
      'Develops gene-screening platforms and targeted trial analytics.',
    owner_name: 'Dr. Yara Weiss',
    employee_count: 460,
    founded_year: 2020,
    government_support_type: 'Biotech research grant',
    government_support_amount: 15000000,
    tax_benefit_percent: 7,
    state_loan_rate_percent: 0,
    support_expires_year: 2029,
    support_risk_level: 'medium',
    price: 19,
    previous_price: 19,
    market_cap: 250000000,
    volatility: 7.2,
    event_sensitivity: 1.35,
  },
  {
    symbol: 'CHIP',
    name: 'ChipNorth Semi',
    sector: 'Semiconductor',
    description:
      'Designs sensor chips for drones, vehicles, and factory robots.',
    owner_name: 'Ethan Zhou',
    employee_count: 1650,
    founded_year: 2011,
    government_support_type: 'Domestic chip subsidy',
    government_support_amount: 45000000,
    tax_benefit_percent: 10,
    state_loan_rate_percent: 1.4,
    support_expires_year: 2033,
    support_risk_level: 'low',
    price: 74,
    previous_price: 74,
    market_cap: 1300000000,
    volatility: 5.9,
    event_sensitivity: 1.2,
  },
  {
    symbol: 'VOLT',
    name: 'VoltStreet Motors',
    sector: 'Automotive',
    description: 'Builds compact electric delivery vehicles for urban fleets.',
    owner_name: 'Karim Weiss',
    employee_count: 2600,
    founded_year: 2015,
    government_support_type: 'EV tax credit',
    government_support_amount: 22000000,
    tax_benefit_percent: 8,
    state_loan_rate_percent: 2,
    support_expires_year: 2031,
    support_risk_level: 'medium',
    price: 28,
    previous_price: 28,
    market_cap: 390000000,
    volatility: 5.6,
    event_sensitivity: 1.1,
  },
  {
    symbol: 'TELA',
    name: 'TelaWave Networks',
    sector: 'Telecom',
    description: 'Runs regional fiber networks and private 5G infrastructure.',
    owner_name: 'Hannah Brooks',
    employee_count: 3100,
    founded_year: 2004,
    government_support_type: 'Rural broadband grant',
    government_support_amount: 30000000,
    tax_benefit_percent: 3,
    state_loan_rate_percent: 1.6,
    support_expires_year: 2030,
    support_risk_level: 'low',
    price: 36,
    previous_price: 36,
    market_cap: 690000000,
    volatility: 2.9,
    event_sensitivity: 0.75,
  },
  {
    symbol: 'MINE',
    name: 'DeepCore Mining',
    sector: 'Mining',
    description:
      'Extracts industrial metals used in batteries, solar panels, and robotics.',
    owner_name: 'Owen Drake',
    employee_count: 5200,
    founded_year: 1992,
    government_support_type: 'Strategic minerals permit',
    government_support_amount: 18000000,
    tax_benefit_percent: 4,
    state_loan_rate_percent: 2.7,
    support_expires_year: 2028,
    support_risk_level: 'high',
    price: 44,
    previous_price: 44,
    market_cap: 760000000,
    volatility: 5.1,
    event_sensitivity: 1.05,
  },
  {
    symbol: 'CLOD',
    name: 'CloudHarbor',
    sector: 'Cloud',
    description:
      'Provides cloud hosting, data warehousing, and AI compute clusters.',
    owner_name: 'Miriam Lang',
    employee_count: 2450,
    founded_year: 2014,
    government_support_type: 'none',
    government_support_amount: 0,
    tax_benefit_percent: 0,
    state_loan_rate_percent: 0,
    support_expires_year: 0,
    support_risk_level: 'none',
    price: 58,
    previous_price: 58,
    market_cap: 940000000,
    volatility: 5.3,
    event_sensitivity: 1.15,
  },
  {
    symbol: 'BANK',
    name: 'CivicTrust Bank',
    sector: 'Banking',
    description:
      'Serves households and municipal projects with conservative lending.',
    owner_name: 'Helena Park',
    employee_count: 4700,
    founded_year: 1987,
    government_support_type: 'Municipal lending guarantee',
    government_support_amount: 35000000,
    tax_benefit_percent: 2,
    state_loan_rate_percent: 2.5,
    support_expires_year: 2032,
    support_risk_level: 'low',
    price: 46,
    previous_price: 46,
    market_cap: 850000000,
    volatility: 2.8,
    event_sensitivity: 0.8,
  },
  {
    symbol: 'PIX',
    name: 'PixelForge Studio',
    sector: 'Gaming',
    description:
      'Creates cross-platform strategy games with collectible cosmetic markets.',
    owner_name: 'Eli Garner',
    employee_count: 520,
    founded_year: 2018,
    government_support_type: 'none',
    government_support_amount: 0,
    tax_benefit_percent: 0,
    state_loan_rate_percent: 0,
    support_expires_year: 0,
    support_risk_level: 'none',
    price: 16,
    previous_price: 16,
    market_cap: 190000000,
    volatility: 6.4,
    event_sensitivity: 1.25,
  },
  {
    symbol: 'HELI',
    name: 'HelioFuel',
    sector: 'Energy',
    description:
      'Produces hydrogen fuel cells and storage modules for industrial sites.',
    owner_name: 'Dana Katz',
    employee_count: 900,
    founded_year: 2017,
    government_support_type: 'Hydrogen transition subsidy',
    government_support_amount: 27000000,
    tax_benefit_percent: 11,
    state_loan_rate_percent: 1.8,
    support_expires_year: 2031,
    support_risk_level: 'medium',
    price: 32,
    previous_price: 32,
    market_cap: 360000000,
    volatility: 5.2,
    event_sensitivity: 1,
  },
  {
    symbol: 'PATH',
    name: 'PathRail Logistics',
    sector: 'Logistics',
    description: 'Optimizes rail freight scheduling and warehouse transfers.',
    owner_name: 'Serena Holt',
    employee_count: 2300,
    founded_year: 2006,
    government_support_type: 'Freight corridor loan',
    government_support_amount: 24000000,
    tax_benefit_percent: 3,
    state_loan_rate_percent: 2.3,
    support_expires_year: 2030,
    support_risk_level: 'medium',
    price: 27,
    previous_price: 27,
    market_cap: 420000000,
    volatility: 3.7,
    event_sensitivity: 1.05,
  },
  {
    symbol: 'CURE',
    name: 'CureLink Bio',
    sector: 'Biotech',
    description:
      'Runs virtual trial recruitment and biomarker matching for clinics.',
    owner_name: 'Dr. Samira Noor',
    employee_count: 620,
    founded_year: 2019,
    government_support_type: 'Clinical data grant',
    government_support_amount: 9000000,
    tax_benefit_percent: 5,
    state_loan_rate_percent: 0,
    support_expires_year: 2028,
    support_risk_level: 'medium',
    price: 23,
    previous_price: 23,
    market_cap: 280000000,
    volatility: 6.8,
    event_sensitivity: 1.3,
  },
  {
    symbol: 'AUTO',
    name: 'AutoMind Drive',
    sector: 'Automotive',
    description:
      'Builds driver-assistance software and fleet safety analytics.',
    owner_name: 'Tomer Ravid',
    employee_count: 1180,
    founded_year: 2016,
    government_support_type: 'Road safety pilot',
    government_support_amount: 8000000,
    tax_benefit_percent: 3,
    state_loan_rate_percent: 0,
    support_expires_year: 2027,
    support_risk_level: 'medium',
    price: 22,
    previous_price: 22,
    market_cap: 310000000,
    volatility: 5.7,
    event_sensitivity: 1.2,
  },
  {
    symbol: 'SHOP',
    name: 'ShopNest Retail',
    sector: 'Retail',
    description:
      'Operates neighborhood commerce software and same-day delivery marketplaces.',
    owner_name: 'Clara Nguyen',
    employee_count: 1750,
    founded_year: 2012,
    government_support_type: 'none',
    government_support_amount: 0,
    tax_benefit_percent: 0,
    state_loan_rate_percent: 0,
    support_expires_year: 0,
    support_risk_level: 'none',
    price: 18,
    previous_price: 18,
    market_cap: 270000000,
    volatility: 4.8,
    event_sensitivity: 1.05,
  },
  {
    symbol: 'CORE',
    name: 'CoreBit Semi',
    sector: 'Semiconductor',
    description:
      'Fabricates low-power processors for mobile devices and robots.',
    owner_name: 'Alex Ren',
    employee_count: 2850,
    founded_year: 2009,
    government_support_type: 'Chip fabrication tax credit',
    government_support_amount: 52000000,
    tax_benefit_percent: 12,
    state_loan_rate_percent: 1.2,
    support_expires_year: 2034,
    support_risk_level: 'low',
    price: 81,
    previous_price: 81,
    market_cap: 1550000000,
    volatility: 5.6,
    event_sensitivity: 1.15,
  },
  {
    symbol: 'ROVR',
    name: 'RoverWorks',
    sector: 'Robotics',
    description:
      'Produces field robots for mines, farms, and disaster response teams.',
    owner_name: 'Iris Novak',
    employee_count: 930,
    founded_year: 2018,
    government_support_type: 'Disaster robotics grant',
    government_support_amount: 13000000,
    tax_benefit_percent: 5,
    state_loan_rate_percent: 2,
    support_expires_year: 2029,
    support_risk_level: 'medium',
    price: 25,
    previous_price: 25,
    market_cap: 330000000,
    volatility: 5.4,
    event_sensitivity: 1.1,
  },
  {
    symbol: 'DATA',
    name: 'DataVault Cloud',
    sector: 'Cloud',
    description:
      'Secures enterprise backups and analytics workloads across regulated industries.',
    owner_name: 'Brian Cole',
    employee_count: 1900,
    founded_year: 2013,
    government_support_type: 'Critical data hosting contract',
    government_support_amount: 19000000,
    tax_benefit_percent: 4,
    state_loan_rate_percent: 1.9,
    support_expires_year: 2031,
    support_risk_level: 'low',
    price: 49,
    previous_price: 49,
    market_cap: 780000000,
    volatility: 4.6,
    event_sensitivity: 1.05,
  },
  {
    symbol: 'WAVE',
    name: 'WaveCell Telecom',
    sector: 'Telecom',
    description:
      'Builds emergency network towers and resilient wireless coverage.',
    owner_name: 'Nora Stein',
    employee_count: 2200,
    founded_year: 2007,
    government_support_type: 'Emergency network support',
    government_support_amount: 17000000,
    tax_benefit_percent: 3,
    state_loan_rate_percent: 2.1,
    support_expires_year: 2029,
    support_risk_level: 'low',
    price: 30,
    previous_price: 30,
    market_cap: 510000000,
    volatility: 3.1,
    event_sensitivity: 0.8,
  },
  {
    symbol: 'GOLD',
    name: 'Aurum Ridge Mining',
    sector: 'Mining',
    description:
      'Mines precious and industrial metals for electronics and energy storage.',
    owner_name: 'Valeria Moss',
    employee_count: 6100,
    founded_year: 1984,
    government_support_type: 'none',
    government_support_amount: 0,
    tax_benefit_percent: 0,
    state_loan_rate_percent: 0,
    support_expires_year: 0,
    support_risk_level: 'none',
    price: 57,
    previous_price: 57,
    market_cap: 910000000,
    volatility: 4.7,
    event_sensitivity: 0.95,
  },
  {
    symbol: 'SEED',
    name: 'SeedNova Agri',
    sector: 'Agriculture',
    description: 'Develops climate-resistant seeds and farm planning software.',
    owner_name: 'Mateo Silva',
    employee_count: 870,
    founded_year: 2016,
    government_support_type: 'Climate agriculture grant',
    government_support_amount: 12000000,
    tax_benefit_percent: 6,
    state_loan_rate_percent: 2.2,
    support_expires_year: 2028,
    support_risk_level: 'medium',
    price: 20,
    previous_price: 20,
    market_cap: 240000000,
    volatility: 4.2,
    event_sensitivity: 1,
  },
  {
    symbol: 'LEARN',
    name: 'LearnSphere',
    sector: 'Education',
    description:
      'Offers AI tutoring, certification exams, and workforce reskilling platforms.',
    owner_name: 'Anika Shah',
    employee_count: 760,
    founded_year: 2017,
    government_support_type: 'Workforce reskilling tender',
    government_support_amount: 10000000,
    tax_benefit_percent: 4,
    state_loan_rate_percent: 0,
    support_expires_year: 2030,
    support_risk_level: 'low',
    price: 14,
    previous_price: 14,
    market_cap: 180000000,
    volatility: 4.5,
    event_sensitivity: 0.95,
  },
  {
    symbol: 'MATR',
    name: 'MatrixFab',
    sector: 'Manufacturing',
    description:
      'Runs modular factories for medical devices, vehicles, and industrial parts.',
    owner_name: 'Kenji Ito',
    employee_count: 3400,
    founded_year: 2001,
    government_support_type: 'Factory resilience loan',
    government_support_amount: 23000000,
    tax_benefit_percent: 7,
    state_loan_rate_percent: 2.4,
    support_expires_year: 2031,
    support_risk_level: 'medium',
    price: 33,
    previous_price: 33,
    market_cap: 620000000,
    volatility: 4.1,
    event_sensitivity: 0.95,
  },
  {
    symbol: 'PAYR',
    name: 'PayRoute Systems',
    sector: 'Fintech',
    description:
      'Provides instant settlement rails for global merchants and creators.',
    owner_name: 'Luca Marin',
    employee_count: 980,
    founded_year: 2015,
    government_support_type: 'none',
    government_support_amount: 0,
    tax_benefit_percent: 0,
    state_loan_rate_percent: 0,
    support_expires_year: 0,
    support_risk_level: 'none',
    price: 41,
    previous_price: 41,
    market_cap: 560000000,
    volatility: 5.5,
    event_sensitivity: 1.15,
  },
  {
    symbol: 'HOME',
    name: 'HomeLoop Consumer',
    sector: 'Consumer',
    description:
      'Sells smart home subscriptions, appliances, and lifestyle services.',
    owner_name: 'Mila Hart',
    employee_count: 1450,
    founded_year: 2011,
    government_support_type: 'none',
    government_support_amount: 0,
    tax_benefit_percent: 0,
    state_loan_rate_percent: 0,
    support_expires_year: 0,
    support_risk_level: 'none',
    price: 26,
    previous_price: 26,
    market_cap: 350000000,
    volatility: 4.3,
    event_sensitivity: 0.95,
  },
  {
    symbol: 'SENT',
    name: 'Sentinel Cyber',
    sector: 'Cybersecurity',
    description:
      'Monitors cloud identity, ransomware risk, and national infrastructure endpoints.',
    owner_name: 'Gideon Cross',
    employee_count: 1250,
    founded_year: 2014,
    government_support_type: 'Infrastructure defense contract',
    government_support_amount: 26000000,
    tax_benefit_percent: 5,
    state_loan_rate_percent: 1.7,
    support_expires_year: 2032,
    support_risk_level: 'low',
    price: 52,
    previous_price: 52,
    market_cap: 820000000,
    volatility: 5.2,
    event_sensitivity: 1.1,
  },
  {
    symbol: 'MOON',
    name: 'MoonGate Launch',
    sector: 'Space',
    description:
      'Builds reusable launch stages and lunar logistics simulation software.',
    owner_name: 'Naomi Pierce',
    employee_count: 980,
    founded_year: 2019,
    government_support_type: 'Exploration milestone grant',
    government_support_amount: 31000000,
    tax_benefit_percent: 6,
    state_loan_rate_percent: 1.6,
    support_expires_year: 2033,
    support_risk_level: 'medium',
    price: 39,
    previous_price: 39,
    market_cap: 500000000,
    volatility: 6.5,
    event_sensitivity: 1.3,
  },
];

export const BOT_TRADERS: BotTraderSeed[] = [
  { name: 'Atlas Quant', cash_balance: 180000, style: 'momentum' },
  { name: 'Harbor Fund', cash_balance: 160000, style: 'value' },
  { name: 'Nova Desk', cash_balance: 140000, style: 'support' },
  { name: 'Pulse Capital', cash_balance: 150000, style: 'aggressive' },
  { name: 'Cedar Algo', cash_balance: 130000, style: 'balanced' },
  { name: 'Orion Market', cash_balance: 170000, style: 'contrarian' },
  { name: 'Flash Scalper', cash_balance: 90000, style: 'scalper' },
  { name: 'Long Horizon', cash_balance: 240000, style: 'investor' },
  { name: 'Panic Desk', cash_balance: 85000, style: 'panic' },
  { name: 'Whale Bidder', cash_balance: 320000, style: 'aggressive' },
  { name: 'Delta Maker', cash_balance: 260000, style: 'market_maker' },
  { name: 'Coin Flip Club', cash_balance: 95000, style: 'random' },
  { name: 'Rate Hawk', cash_balance: 150000, style: 'value' },
  { name: 'Green Fund', cash_balance: 170000, style: 'support' },
  { name: 'Risk Runner', cash_balance: 120000, style: 'momentum' },
  { name: 'Patient Capital', cash_balance: 230000, style: 'investor' },
  { name: 'Red Candle', cash_balance: 80000, style: 'panic' },
  { name: 'Micro Tick', cash_balance: 70000, style: 'scalper' },
  { name: 'Deep Value', cash_balance: 210000, style: 'value' },
  { name: 'State Watch', cash_balance: 165000, style: 'support' },
  { name: 'Noise Trader', cash_balance: 90000, style: 'random' },
  { name: 'Heavy Buyer', cash_balance: 280000, style: 'aggressive' },
  { name: 'Anchor Maker', cash_balance: 250000, style: 'market_maker' },
  { name: 'Reversal Lab', cash_balance: 145000, style: 'contrarian' },
  { name: 'Cloud Chaser', cash_balance: 155000, style: 'momentum' },
  { name: 'Bio Venture', cash_balance: 190000, style: 'investor' },
  { name: 'Supply Desk', cash_balance: 130000, style: 'balanced' },
  { name: 'Macro Bot', cash_balance: 175000, style: 'value' },
  { name: 'Gamma Flow', cash_balance: 115000, style: 'scalper' },
  { name: 'Retail Crowd', cash_balance: 105000, style: 'random' },
  { name: 'Defensive Fund', cash_balance: 220000, style: 'support' },
  { name: 'Breaker Algo', cash_balance: 125000, style: 'panic' },
];

export const EVENT_TEMPLATES: EventTemplateSeed[] = [
  {
    title: 'Central bank raises rates',
    description:
      'Higher rates help bank margins but pressure growth companies and consumer borrowing.',
    category: 'Interest Rates',
    scope: 'global',
    price_impact_percent: -1,
    sector_impacts: {
      Banking: 5,
      AI: -4,
      Cloud: -4,
      Robotics: -3,
      Automotive: -3,
      Retail: -2,
      Energy: 0.4,
    },
  },
  {
    title: 'Central bank cuts rates',
    description:
      'Cheaper capital boosts growth stocks while banks lose some lending spread.',
    category: 'Interest Rates',
    scope: 'global',
    price_impact_percent: 1.5,
    sector_impacts: {
      Banking: -2,
      AI: 4,
      Cloud: 4,
      Biotech: 3,
      Automotive: 3,
      Retail: 2,
    },
  },
  {
    title: 'Border war risk rises',
    description:
      'A military escalation threatens freight routes and raises demand for security technology.',
    category: 'War',
    scope: 'global',
    price_impact_percent: -1.5,
    sector_impacts: {
      Logistics: -6,
      Energy: 3,
      Cybersecurity: 5,
      Space: 3,
      Retail: -3,
      Banking: -2,
    },
  },
  {
    title: 'Regional defense alliance signed',
    description:
      'Governments coordinate drone, satellite, and cyber procurement.',
    category: 'Politics',
    scope: 'global',
    price_impact_percent: 1,
    sector_impacts: {
      Space: 6,
      Cybersecurity: 5,
      Robotics: 3,
      AI: 2,
      Logistics: 1,
    },
  },
  {
    title: 'Severe drought warning',
    description:
      'Dry weather pressures traditional agriculture but increases demand for advanced food systems.',
    category: 'Weather',
    scope: 'global',
    price_impact_percent: -0.8,
    sector_impacts: { Agriculture: 4, Retail: -2, Logistics: -1, Energy: 1 },
  },
  {
    title: 'Chip shortage expands',
    description:
      'Limited supply of machine-vision chips delays robots, cars, and cloud equipment.',
    category: 'Logistics',
    scope: 'global',
    price_impact_percent: -1,
    sector_impacts: {
      Semiconductor: 5,
      Robotics: -4,
      Automotive: -4,
      AI: -2,
      Cloud: -2,
      Gaming: -2,
    },
  },
  {
    title: 'Major cloud outage',
    description:
      'A fictional regional outage shakes confidence in cloud infrastructure.',
    category: 'Technology',
    scope: 'sector',
    target_sector: 'Cloud',
    price_impact_percent: -7,
    sector_impacts: { Cybersecurity: 2, Telecom: 1 },
  },
  {
    title: 'AI licensing relief',
    description: 'Regulators delay strict AI licensing rules.',
    category: 'Regulation',
    scope: 'sector',
    target_sector: 'AI',
    price_impact_percent: 7,
    sector_impacts: { Cloud: 2, Semiconductor: 2 },
  },
  {
    title: 'Biotech trial breakthrough',
    description:
      'A new screening approach improves trial success expectations.',
    category: 'Company Reports',
    scope: 'sector',
    target_sector: 'Biotech',
    price_impact_percent: 8,
  },
  {
    title: 'Biotech safety review',
    description: 'Regulators request more data from several clinical programs.',
    category: 'Regulation',
    scope: 'sector',
    target_sector: 'Biotech',
    price_impact_percent: -7,
  },
  {
    title: 'Energy storage subsidy extended',
    description:
      'Lawmakers extend support for batteries, solar grids, and hydrogen storage.',
    category: 'Energy',
    scope: 'global',
    price_impact_percent: 1,
    sector_impacts: { Energy: 6, Mining: 2, Manufacturing: 1 },
  },
  {
    title: 'Oil transit disruption',
    description:
      'A fictional transit disruption raises energy prices and freight costs.',
    category: 'Energy',
    scope: 'global',
    price_impact_percent: -1,
    sector_impacts: { Energy: 5, Logistics: -4, Automotive: -2, Retail: -2 },
  },
  {
    title: 'Retail holiday surge',
    description:
      'Consumer spending beats expectations during a simulated holiday cycle.',
    category: 'Economy',
    scope: 'global',
    price_impact_percent: 1,
    sector_impacts: { Retail: 5, Consumer: 4, Logistics: 2, Fintech: 2 },
  },
  {
    title: 'Consumer confidence drops',
    description:
      'Households delay discretionary purchases and rotate into savings.',
    category: 'Economy',
    scope: 'global',
    price_impact_percent: -1.5,
    sector_impacts: { Retail: -5, Consumer: -4, Gaming: -2, Banking: 1 },
  },
  {
    title: 'Mining permit fast-track',
    description: 'Strategic minerals projects receive faster approval.',
    category: 'Regulation',
    scope: 'sector',
    target_sector: 'Mining',
    price_impact_percent: 6,
    sector_impacts: { Automotive: 1, Semiconductor: 1 },
  },
  {
    title: 'Mine safety incident',
    description:
      'A major site shutdown reduces supply and raises safety costs.',
    category: 'Catastrophes',
    scope: 'sector',
    target_sector: 'Mining',
    price_impact_percent: -6,
  },
  {
    title: 'Game platform revenue beat',
    description: 'In-app purchases and esports activity surprise investors.',
    category: 'Company Reports',
    scope: 'sector',
    target_sector: 'Gaming',
    price_impact_percent: 6,
  },
  {
    title: 'Mobile privacy rule tightens',
    description:
      'New app tracking restrictions pressure game and retail ad efficiency.',
    category: 'Regulation',
    scope: 'global',
    price_impact_percent: -0.5,
    sector_impacts: { Gaming: -5, Retail: -3, Consumer: -2, Cybersecurity: 1 },
  },
  {
    title: 'Telecom spectrum auction',
    description:
      'Telecom operators gain access to valuable spectrum but face high upfront costs.',
    category: 'Regulation',
    scope: 'sector',
    target_sector: 'Telecom',
    price_impact_percent: 3,
    sector_impacts: { Banking: 1 },
  },
  {
    title: 'Satellite launch failure',
    description:
      'A fictional launch failure delays space infrastructure timelines.',
    category: 'Catastrophes',
    scope: 'sector',
    target_sector: 'Space',
    price_impact_percent: -8,
  },
  {
    title: 'Successful lunar logistics test',
    description:
      'A milestone test improves confidence in space infrastructure companies.',
    category: 'Technology',
    scope: 'sector',
    target_sector: 'Space',
    price_impact_percent: 8,
  },
  {
    title: 'Automotive battery recall',
    description:
      'EV suppliers face replacement costs and delayed fleet deliveries.',
    category: 'Company Reports',
    scope: 'sector',
    target_sector: 'Automotive',
    price_impact_percent: -7,
    sector_impacts: { Energy: -1, Semiconductor: -1 },
  },
  {
    title: 'Fleet electrification mandate',
    description: 'Cities accelerate electric delivery fleet purchases.',
    category: 'Politics',
    scope: 'global',
    price_impact_percent: 1,
    sector_impacts: { Automotive: 6, Energy: 3, Semiconductor: 2, Mining: 2 },
  },
  {
    title: 'Cyber attack wave',
    description:
      'Utilities and retailers increase emergency security spending.',
    category: 'Technology',
    scope: 'global',
    price_impact_percent: -0.5,
    sector_impacts: { Cybersecurity: 8, Cloud: -2, Energy: -2, Retail: -2 },
  },
  {
    title: 'Ransomware insurance rule',
    description:
      'Insurers require stronger cyber controls before coverage renewals.',
    category: 'Regulation',
    scope: 'sector',
    target_sector: 'Cybersecurity',
    price_impact_percent: 6,
  },
  {
    title: 'Factory input costs rise',
    description: 'Raw material and labor costs pressure manufacturers.',
    category: 'Economy',
    scope: 'sector',
    target_sector: 'Manufacturing',
    price_impact_percent: -5,
    sector_impacts: { Retail: -1, Automotive: -1 },
  },
  {
    title: 'Factory automation credit',
    description: 'A new tax credit supports robots and modular factories.',
    category: 'Politics',
    scope: 'global',
    price_impact_percent: 1,
    sector_impacts: { Robotics: 5, Manufacturing: 4, AI: 2 },
  },
  {
    title: 'Cloud AI compute boom',
    description:
      'Demand for AI compute pushes cloud and semiconductor orders higher.',
    category: 'Technology',
    scope: 'global',
    price_impact_percent: 1.5,
    sector_impacts: { Cloud: 6, Semiconductor: 5, AI: 4, Energy: 1 },
  },
  {
    title: 'Data residency law',
    description:
      'New data rules favor local cloud and cybersecurity providers.',
    category: 'Regulation',
    scope: 'global',
    price_impact_percent: 0.5,
    sector_impacts: { Cloud: 4, Cybersecurity: 3, Telecom: 1 },
  },
  {
    title: 'Payment fraud scare',
    description:
      'A fraud wave pressures payment platforms and merchant settlement tools.',
    category: 'Crypto Market',
    scope: 'sector',
    target_sector: 'Fintech',
    price_impact_percent: -6,
    sector_impacts: { Cybersecurity: 2 },
  },
  {
    title: 'Stablecoin settlement approval',
    description: 'Regulators approve new simulated settlement rails.',
    category: 'Crypto Market',
    scope: 'sector',
    target_sector: 'Fintech',
    price_impact_percent: 7,
  },
  {
    title: 'Education tax credit',
    description:
      'Schools receive incentives to buy digital learning and training tools.',
    category: 'Politics',
    scope: 'sector',
    target_sector: 'Education',
    price_impact_percent: 6,
  },
  {
    title: 'Education procurement delay',
    description: 'Budget committees postpone a large digital-learning program.',
    category: 'Politics',
    scope: 'sector',
    target_sector: 'Education',
    price_impact_percent: -5,
  },
  {
    title: 'Robot warehouse accident',
    description: 'A safety investigation slows robotics deployments.',
    category: 'Catastrophes',
    scope: 'sector',
    target_sector: 'Robotics',
    price_impact_percent: -6,
  },
  {
    title: 'Robotics productivity study',
    description: 'A major study shows warehouse automation improving margins.',
    category: 'Technology',
    scope: 'sector',
    target_sector: 'Robotics',
    price_impact_percent: 6,
  },
  {
    title: 'Port congestion returns',
    description: 'Congestion hits container routes and raises shipping delays.',
    category: 'Logistics',
    scope: 'sector',
    target_sector: 'Logistics',
    price_impact_percent: -5,
    sector_impacts: { Retail: -1, Manufacturing: -1 },
  },
  {
    title: 'Freight corridor opens',
    description:
      'A new logistics corridor improves delivery times and fleet utilization.',
    category: 'Logistics',
    scope: 'sector',
    target_sector: 'Logistics',
    price_impact_percent: 5,
  },
  {
    title: 'Semiconductor export limits',
    description:
      'Export controls pressure chipmakers and their largest customers.',
    category: 'Politics',
    scope: 'global',
    price_impact_percent: -1.5,
    sector_impacts: { Semiconductor: -7, AI: -3, Cloud: -3, Automotive: -2 },
  },
  {
    title: 'Semiconductor fabrication grant',
    description: 'New domestic fabrication grants improve long-term capacity.',
    category: 'Politics',
    scope: 'sector',
    target_sector: 'Semiconductor',
    price_impact_percent: 7,
  },
  {
    title: 'Luxury demand surge',
    description: 'Premium consumer brands report stronger basket sizes.',
    category: 'Economy',
    scope: 'global',
    price_impact_percent: 0.8,
    sector_impacts: { Consumer: 5, Retail: 3, Fintech: 1 },
  },
  {
    title: 'Housing slowdown',
    description:
      'A construction slowdown reduces demand for home products and materials.',
    category: 'Economy',
    scope: 'global',
    price_impact_percent: -1,
    sector_impacts: { Consumer: -4, Manufacturing: -3, Banking: -1 },
  },
  {
    title: 'Food security alliance',
    description: 'Several states coordinate food supply investments.',
    category: 'Politics',
    scope: 'sector',
    target_sector: 'Agriculture',
    price_impact_percent: 5,
  },
  {
    title: 'Crop disease outbreak',
    description: 'A fictional crop disease threatens open-field supply.',
    category: 'Weather',
    scope: 'sector',
    target_sector: 'Agriculture',
    price_impact_percent: -4,
    sector_impacts: { Retail: -1 },
  },
  {
    title: 'Telecom infrastructure storm damage',
    description:
      'Severe weather damages towers but boosts emergency network spending later.',
    category: 'Weather',
    scope: 'sector',
    target_sector: 'Telecom',
    price_impact_percent: -4,
  },
  {
    title: 'Emergency network funding',
    description: 'Governments fund resilient towers and backup connectivity.',
    category: 'Politics',
    scope: 'sector',
    target_sector: 'Telecom',
    price_impact_percent: 5,
  },
  {
    title: 'Global risk-on session',
    description:
      'Players rotate from cash into growth sectors after calm macro data.',
    category: 'Economy',
    scope: 'global',
    price_impact_percent: 2.5,
    sector_impacts: { AI: 3, Cloud: 3, Biotech: 2, Gaming: 2, Banking: -0.5 },
  },
  {
    title: 'Global risk-off session',
    description:
      'A macro shock pushes players toward cash and defensive sectors.',
    category: 'Economy',
    scope: 'global',
    price_impact_percent: -2.5,
    sector_impacts: {
      Banking: 1,
      Telecom: 1,
      Energy: 0.5,
      AI: -3,
      Biotech: -3,
      Gaming: -2,
    },
  },
  {
    title: 'AERO procurement rumor',
    description:
      'AeroVista Drones is rumored to win a port inspection contract.',
    category: 'Company Reports',
    scope: 'company',
    target_symbol: 'AERO',
    price_impact_percent: 9,
  },
  {
    title: 'SOLR subsidy review',
    description:
      'Solara Grid may receive longer state support for microgrid projects.',
    category: 'Energy',
    scope: 'company',
    target_symbol: 'SOLR',
    price_impact_percent: 7,
  },
  {
    title: 'CHIP supply expansion',
    description: 'ChipNorth Semi announces new capacity for vision sensors.',
    category: 'Company Reports',
    scope: 'company',
    target_symbol: 'CHIP',
    price_impact_percent: 8,
  },
  {
    title: 'BRIX loan loss warning',
    description: 'Brixon Bank warns that small business defaults may rise.',
    category: 'Company Reports',
    scope: 'company',
    target_symbol: 'BRIX',
    price_impact_percent: -7,
  },
  {
    title: 'MOON milestone payment',
    description:
      'MoonGate Launch receives a milestone payment after a successful test.',
    category: 'Company Reports',
    scope: 'company',
    target_symbol: 'MOON',
    price_impact_percent: 9,
  },
];

export const STARTER_OFFERS = [
  {
    sku: 'starter_tokens_250',
    title: 'Starter Pack',
    description: 'Adds 250 permanent tokens to the verified account.',
    type: 'token_pack' as const,
    price_usd: 1.99,
    token_reward: 250,
  },
  {
    sku: 'trader_tokens_800',
    title: 'Trader Pack',
    description:
      'Adds 800 permanent tokens for sessions, modes, and future features.',
    type: 'token_pack' as const,
    price_usd: 4.99,
    token_reward: 800,
  },
  {
    sku: 'investor_tokens_2200',
    title: 'Investor Pack',
    description: 'Adds 2,200 permanent tokens for premium progression.',
    type: 'token_pack' as const,
    price_usd: 9.99,
    token_reward: 2200,
  },
];

export const SESSION_STARTERS = [
  {
    sku: 'session_cash_1000',
    title: 'Standard Session',
    cash: 1000,
    token_cost: 0,
  },
  {
    sku: 'session_cash_5000',
    title: 'Funded Session',
    cash: 5000,
    token_cost: 120,
  },
  {
    sku: 'session_cash_15000',
    title: 'Pro Session',
    cash: 15000,
    token_cost: 300,
  },
  {
    sku: 'session_cash_50000',
    title: 'Investor Session',
    cash: 50000,
    token_cost: 850,
  },
];

export const ACHIEVEMENT_DEFINITIONS = [
  {
    code: 'first_trade',
    title: 'First Trade',
    target: 1,
    metric: 'total_trades',
    token_reward: 25,
  },
  {
    code: 'ten_profitable_trades',
    title: '10 Profitable Trades',
    target: 10,
    metric: 'profitable_trades',
    token_reward: 100,
  },
  {
    code: 'hundred_trades',
    title: '100 Trades',
    target: 100,
    metric: 'total_trades',
    token_reward: 200,
  },
  {
    code: 'first_million',
    title: 'First Million',
    target: 1000000,
    metric: 'net_worth',
    token_reward: 500,
  },
  {
    code: 'ten_day_streak',
    title: '10 Day Streak',
    target: 10,
    metric: 'login_streak',
    token_reward: 150,
  },
  {
    code: 'break_even_week',
    title: 'Break-even Week',
    target: 1,
    metric: 'weekly_non_loss',
    token_reward: 120,
  },
];

export const DAILY_QUEST_DEFINITIONS = [
  {
    code: 'buy_ai',
    title: 'Buy AI Shares',
    target: 1,
    metric: 'buy_sector:AI',
    token_reward: 20,
  },
  {
    code: 'five_trades',
    title: 'Make 5 Trades',
    target: 5,
    metric: 'total_trades',
    token_reward: 35,
  },
  {
    code: 'profit_three_percent',
    title: 'Earn 3% Profit',
    target: 3,
    metric: 'profit_percent',
    token_reward: 45,
  },
  {
    code: 'earn_5000',
    title: 'Earn $5,000',
    target: 5000,
    metric: 'cash_profit',
    token_reward: 60,
  },
];

export const NEWS_TEMPLATES = EVENT_TEMPLATES.slice(0, 24).map(
  (event, index) => ({
    slug: event.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, ''),
    title: event.title,
    summary: event.description,
    category: event.category,
    target_sector: event.target_sector,
    target_symbol: event.target_symbol,
    expected_impact_percent: event.price_impact_percent,
    probability_percent: Math.min(82, 48 + ((index * 7) % 35)),
    severity:
      Math.abs(event.price_impact_percent) >= 7
        ? 'high'
        : Math.abs(event.price_impact_percent) >= 4
          ? 'medium'
          : 'low',
    days_from_now: (index % 7) + 1,
  }),
);
